project = 'talent-IQ'
author = 'talent-IQ contributors'
release = 'Prototype documentation / 2026-09-18'
extensions = []
root_doc = 'index'
exclude_patterns = ['_build']
html_theme = 'alabaster'
html_title = 'talent-IQ developer documentation'
html_static_path = ['_static']
html_css_files = ['custom.css']
html_theme_options = {'description': 'Understand the prototype. Set up carefully. Contribute with evidence.', 'fixed_sidebar': True}
html_show_copyright = False
nitpicky = True
